### ISSUE TITLE
Erreur sur le formulaire

### ISSUE THREAD

**Issue by WilliamDarcy** [HowSharpIsC/TPEquipe#2]
Si je rentre le formulaire suivant: 
![image](https://user-images.githubusercontent.com/10536519/46722514-f2b52d80-cc75-11e8-8cb8-37406e8d59c6.png)
J'obtiens ceci 
![image](https://user-images.githubusercontent.com/10536519/46722631-445db800-cc76-11e8-990b-84803d539782.png)
La boucle est sans fin.

**Comment by HowSharpIsC** [comment]
J'ai ajouté un filtre pour recevoir uniquement des valeurs entières, un filtre pour que la valeur de départ ne soit pas supérieur à celle de fin et un filtre pour que le pas soit strictement supérieur à 0.
